{
 "title": "Docker",
 "description": "Docker exporter dashboard \nhttps://github.com/h3rmt/docker-exporter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "multi", "query": "10000" },
   { "name": "source", "label": "Source", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(docker_container_info,hostname)"
    }
   },
   {
    "name": "filter",
    "label": "Filter",
    "query": {
     "query": "label_values(docker_container_info{hostname=~\"$hostname\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Per Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services uptime",
   "type": "stat",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by(hostname) (docker_container_info{name=~\"$filter\", hostname=~\"$hostname\"} * on(container_id) group_left(name) docker_container_state)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 12, "w": 7, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(hostname) (docker_container_info{name=~\"$filter\", hostname=~\"$hostname\"} * on(container_id) group_left(name) docker_container_state)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Services Restarting",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by(hostname) (docker_container_info{name=~\"$filter\", hostname=~\"$hostname\"} * on(container_id) group_left(name) docker_container_state == 3) or count by(hostname) (docker_container_info{name=~\"$filter\", hostname=~\"$hostname\"} * on(container_id) group_left(name) docker_container_state) * 0 ",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Services Dead",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by(hostname) (docker_container_info{name=~\"$filter\", hostname=~\"$hostname\"} * on(container_id) group_left(name) docker_container_state == 6) or count by(hostname) (docker_container_info{name=~\"$filter\", hostname=~\"$hostname\"} * on(container_id) group_left(name) docker_container_state) * 0 ",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Services Exited",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by(hostname) (docker_container_info{name=~\"$filter\", hostname=~\"$hostname\"} * on(container_id) group_left(name) docker_container_state == 5) or count by(hostname) (docker_container_info{name=~\"$filter\", hostname=~\"$hostname\"} * on(container_id) group_left(name) docker_container_state) * 0 ",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "CPU per Host",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(hostname) (docker_container_info{name=~\"$filter\", hostname=~\"$hostname\"} * on(container_id) group_left() rate(docker_container_cpu_user_microseconds_total[$__rate_interval]) / $multi)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Memory usage per host",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "sum by (hostname) (docker_container_info{name=~\"$filter\", hostname=~\"$hostname\"} * on(container_id) group_left()\ndocker_container_mem_usage_kib)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Per Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "docker_container_info{name=~\"$filter\", hostname=~\"$hostname\"} * on(container_id) group_left() rate(docker_container_cpu_user_microseconds_total[$__rate_interval]) / $multi",
     "legendFormat": "{{name}}({{hostname}})"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "docker_container_info{name=~\"$filter\", hostname=~\"$hostname\"} * on(container_id) group_left() docker_container_mem_usage_kib",
     "legendFormat": "{{name}}({{hostname}})"
    }
   ]
  },
  {
   "title": "Network Output",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "docker_container_info{name=~\"$filter\", hostname=~\"$hostname\"} * on(container_id) group_left() rate(docker_container_net_send_bytes_total[$__rate_interval]) * 8",
     "legendFormat": "R {{name}}({{hostname}})"
    },
    {
     "expr": "docker_container_info{name=~\"$filter\", hostname=~\"$hostname\"} * on(container_id) group_left() docker_container_net_send_bytes_total",
     "legendFormat": "F {{name}}({{hostname}})"
    }
   ]
  },
  {
   "title": "Network input",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "docker_container_info{name=~\"$filter\", hostname=~\"$hostname\"} * on(container_id) group_left() rate(docker_container_net_receive_bytes_total[$__rate_interval]) * 8",
     "legendFormat": "R {{name}}({{hostname}})"
    },
    {
     "expr": "docker_container_info{name=~\"$filter\", hostname=~\"$hostname\"} * on(container_id) group_left() docker_container_net_receive_bytes_total",
     "legendFormat": "F {{name}}({{hostname}})"
    }
   ]
  },
  {
   "title": "Read From Disk",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "docker_container_info{name=~\"$filter\", hostname=~\"$hostname\"} * on(container_id) group_left() rate(docker_container_block_input_total[$__rate_interval])",
     "legendFormat": "R {{name}}({{hostname}})"
    },
    {
     "expr": "docker_container_info{name=~\"$filter\", hostname=~\"$hostname\"} * on(container_id) group_left() docker_container_block_input_total",
     "legendFormat": "F {{name}}({{hostname}})"
    }
   ]
  },
  {
   "title": "Write To Disk",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "docker_container_info{name=~\"$filter\", hostname=~\"$hostname\"} * on(container_id) group_left() rate(docker_container_block_output_total[$__rate_interval])",
     "legendFormat": "R {{name}}({{hostname}})"
    },
    {
     "expr": "docker_container_info{name=~\"$filter\", hostname=~\"$hostname\"} * on(container_id) group_left() docker_container_block_output_total",
     "legendFormat": "F {{name}}({{hostname}})"
    }
   ]
  },
  {
   "title": "Bytes Changed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "docker_container_info{name=~\"$filter\", hostname=~\"$hostname\"} * on(container_id) group_left() docker_container_rw_size_bytes",
     "legendFormat": "{{name}}({{hostname}})"
    }
   ]
  },
  {
   "title": "Size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "docker_container_info{name=~\"$filter\", hostname=~\"$hostname\"} * on(container_id) group_left() docker_container_rootfs_size_bytes",
     "legendFormat": "{{name}}({{hostname}})"
    }
   ]
  }
 ]
}